openapi: 3.0.3
info:
  title: Handläggning API
  version: 1.0.2
  description: API för att hämta och lagra handläggningsinformation.

paths:
  /handlaggning:
    post:
      tags: [HandlaggningController]
      operationId: postHandlaggning
      summary: Skapa en ny handläggning
      description: Skapa en ny handläggning för ett specifikt yrkande
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yrkandeId:
                  type: string
                  format: uuid
                  description: Yrkandets id
              required:
                - yrkandeId
      responses:
        '201':
          description: Handläggning skapat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt yrkandeId)

  /handlaggning/{handlaggningId}:
    get:
      tags: [HandlaggningController]
      operationId: getHandlaggning
      summary: Hämta handläggning
      description: Hämta handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Handläggning hämtat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)
    put:
      tags: [HandlaggningController]
      operationId: putHandlaggning
      summary: Uppdatera handläggning
      description: Uppdatera handläggning för handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutHandlaggningRequest'
      responses:
        '200':
          description: Handläggning uppdaterat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)

  /handlaggning/{handlaggningId}/ersattning:
    patch:
      tags: [HandlaggningController]
      operationId: patchHandlaggning
      summary: Uppdatera beslutsutfall för handläggning
      description: Uppdatera beslutsutfall och avslagsanledning för ersättningar i en handläggning
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchHandlaggningRequest'
      responses:
        '200':
          description: Handläggning uppdaterad OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)

components:
  schemas:
    Handlaggning:
      type: object
      description: Handläggning, ärendeinstans
      properties:
        id:
          type: string
          description: Handläggningens unika ID
          format: uuid
        version:
          type: string
          description: Handläggningens version
        yrkandeId:
          type: string
          description: Yrkandets unika ID
          format: uuid
        processinstansId:
          type: string
          description: BPMN processinstansens unika ID
          format: uuid
        skapadTS:
          type: string
          description: DateTime när handläggning skapades, enligt ISO 8601
          format: date-time
        avslutadTS:
          type: string
          description: DateTime när handläggning avslutades, enligt ISO 8601
          format: date-time
        handlaggningspecifikation:
          $ref: '#/components/schemas/Handlaggningspecifikation'
      required:
        - id
        - processinstansId
        - yrkande

    UppgiftStatus:
      type: string
      description: Uppgiftens status
      enum:
        - PLANERAD
        - TILLDELAD
        - AVSLUTAD

    Period:
      type: object
      description: En tidsperiod med start och slut
      properties:
        start:
          type: string
          format: date-time
          description: Startdatum/tid för perioden, enligt ISO 8601
        slut:
          type: string
          format: date-time
          description: Slutdatum/tid för perioden, enligt ISO 8601
      required:
        - start
        - slut

    Handlaggningspecifikation:
      type: object
      description: Handläggningspecifikation, ärendeslag
      properties:
        id:
          type: string
          description: Handläggningspecifikationens unika ID
          format: uuid
        version:
          type: string
          description: Handläggningspecifikationens version
        bpmn:
          type: string
          description: BPMN processbeskrivning
        namn:
          type: string
          description: Namnet på handläggningspecifikationen
        beskrivning:
          type: string
          description: Beskrivning av handläggningspecifikationen
        uppgiftspecifikation:
          type: array
          description: En eller flera uppgiftsspecifikationer som ingår i handläggningspecifikationen
          items:
            $ref: '#/components/schemas/Uppgiftspecifikation'
      required:
        - id

    Uppgift:
      type: object
      description: Uppgift
      properties:
        id:
          type: string
          description: Uppgiftens ID
          format: uuid
        version:
          type: string
          description: Uppgiftens version
        skapadTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften skapades, enligt ISO 8601
        utfordTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften utfördes, enligt ISO 8601
          nullable: true
        planeradTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften är planerad att utföras, enligt ISO 8601
          nullable: true
        utforarId:
          type: string
          description: Utförarens ID
          format: uuid
          nullable: true
        handlaggningId:
          type: string
          description: Handläggingens Id
          format: uuid
        uppgiftStatus:
          $ref: '#/components/schemas/UppgiftStatus'
        FSSAinformation:
          $ref: '#/components/schemas/FSSAinformation'
        uppgiftspecifikation:
          $ref: '#/components/schemas/Uppgiftspecifikation'
        underlag:
          type: array
          description: Ett eller flera underlag som uppgiften använder sig av
          items:
            $ref: '#/components/schemas/Underlag'

    Underlag:
      type: object
      properties:
        typ:
          type: string
          description: Specificerar vilken typ av underlag det är
        version:
          type: string
          description: Specificerar vilken version av underlags typ det är
        data:
          type: string
          description: All data i underlaget i formatet JSON

    Uppgiftspecifikation:
      type: object
      description: Uppgiftsspecifikation
      properties:
        id:
          type: string
          description: Uppgiftsspecifikationens unika ID
          format: uuid
        version:
          type: string
          description: Uppgiftsspecifikationens version
        namn:
          type: string
          description: Namnet på uppgiftsspecifikationen
        uppgiftbeskrivning:
          description: Beskrivning av uppgiften i mer detalj
        verksamhetslogik:
          description: Beteckning för verksamhetslogiken i uppgiften
          $ref: '#/components/schemas/Verksamhetslogik'
        roll:
          type: string
          description: Behörighetsroll för uppgiften
        applikationsId:
          description: ID för applikation som hanterar uppgiften
          type: string
        applikationsVersion:
          description: Version för applikation som hanterar uppgiften
          type: string
        regel:
          description: En regler som styr uppgiften
          $ref: '#/components/schemas/Regel'
        uppgiftsGui:
          type: string
          description: GUI komponent för uppgiften
      required:
        - id

    Verksamhetslogik:
      type: string
      description: Verksamhetslogik
      enum:
        - A
        - B
        - C

    FSSAinformation:
      type: string
      enum:
        - HANDLAGGNING_PAGAR
        - VANTAR_PA_INFO_FRAN_ANNAN_PART
        - VANTAR_PA_INFO_FRAN_KUND

    Regel:
      type: object
      description: Regel
      properties:
        id:
          type: string
          format: uuid
          description: Regelns unika ID
        version:
          type: string
          description: Version av regeln
        lagrum:
          description: Ett Lagrum som Regeln hänvisar till
          $ref: '#/components/schemas/Lagrum'
      required:
        - id

    Lagrum:
      type: object
      description: Lagrum
      properties:
        id:
          type: string
          description: Lagrummets unika ID
          format: uuid
        version:
          type: string
          description: Lagrummets version
        giltigFrom:
          type: string
          description: DateTime för starttiden av giltighet, enligt ISO 8601
          format: date-time
        giltigTom:
          type: string
          description: DateTime för sluttiden av giltighet, enligt ISO 8601
          format: date-time
          nullable: true
        forfattning:
          type: string
          description: Avser vilken författning Lagrummet är av
        kapitel:
          type: string
          description: Avser vilket kapitel av författningen Lagrummet är av
        paragraf:
          type: string
          description: Avser vilket paragraf i kapitlet Lagrummet är av
        stycke:
          type: string
          description: Avser vilket stycke i paragrafen Lagrummet är av
        punkt:
          type: string
          description: Avser vilken punkt i stycket Lagrummet är av
      required:
        - id

    Ersattning:
      type: object
      description: Ersättning kopplad till ett yrkande
      properties:
        id:
          type: string
          description: Ersättningens unika ID
          format: uuid
        belopp:
          type: integer
          description: Ersättningsbelopp
        berakningsgrund:
          $ref: '#/components/schemas/Berakningsgrund'
        beloppstyp:
          $ref: '#/components/schemas/Beloppstyp'
        ersattningstyp:
          $ref: '#/components/schemas/Ersattningstyp'
        periodisering:
          $ref: '#/components/schemas/Periodisering'
        omfattning:
          type: integer
          description: Omfattning för ersättningen (i procent, 50 = 50%)
        beslutsutfall:
          $ref: '#/components/schemas/Beslutsutfall'
        avslagsanledning:
          type: string
          nullable: true
          description: Anledning till avslag
        produceratResultat:
          $ref: '#/components/schemas/ProduceratResultat'

    Berakningsgrund:
      type: string
      description: Grunden för beräkning
      enum:
        - LON
        - FASTBELOPP

    Beloppstyp:
      type: string
      description: Typ av belopp
      enum:
        - INKOMSTBASERAD
        - GRUNDBELOPP

    Ersattningstyp:
      type: object
      description: Ersättningstyp enligt lagrum
      properties:
        id:
          type: string
          format: uuid
          description: Id för ersättningstyp
        namn:
          type: string
          description: Namn på ersättningstyp
      example: 
        id: "314454e9-ca6d-4fa9-9ec5-e724fc58112f"
        description: "Hundbidrag"

    Periodisering:
      type: string
      description: Periodisering av ersättning
      enum:
        - MANAD
        - VECKA
        - DAG
        - ENGANGS

    ProduceratResultat:
      type: object
      description: Producerat resultat kopplat till en ersättning
      properties:
        id:
          type: string
          format: uuid
          description: Producerat resultatets unika ID
        version:
          type: string
          description: Version av producerat resultat
        from:
          type: string
          format: date-time
          description: Startdatum/tid då resultatet gäller från, enligt ISO 8601
        tom:
          type: string
          format: date-time
          description: Slutdatum/tid då resultatet gäller till, enligt ISO 8601
        status:
          $ref: '#/components/schemas/Ersattningsstatus'

    Ersattningsstatus:
      type: string
      description: Ersättningsstatus
      enum:
        - PLANERAT
        - YRKAT
        - UNDER_UTREDNING
        - FASTSTALLT_UNDER_UTREDNING
        - FASTSTALLT

    GetHandlaggningResponse:
      type: object
      description: Svar vid hämtning av handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning

    PutHandlaggningRequest:
      type: object
      description: Data som krävs för att uppdatera ett handläggning
      properties:
        uppgift:
          $ref: '#/components/schemas/Uppgift'
      required:
        - uppgift

    PutHandlaggningResponse:
      type: object
      description: Svar vid uppdatering av handläggning
      properties:
        uppgift:
          $ref: '#/components/schemas/Uppgift'
      required:
        - uppgift

    PostHandlaggningResponse:
      type: object
      description: Svar vid skapande av en ny handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning

    Beslutsutfall:
      type: string
      description: Beslutsutfall för ersättning
      enum:
        - JA
        - NEJ
        - FU

    UpdateErsattning:
      type: object
      description: Uppdatering av beslutsutfall för en ersättning
      properties:
        ersattningId:
          type: string
          format: uuid
          description: Ersättningens unika ID
        beslutsutfall:
          $ref: '#/components/schemas/Beslutsutfall'
          nullable: true
        avslagsanledning:
          type: string
          nullable: true
          description: Anledning till avslag
        ErsattningsStatus:
          $ref: '#/components/schemas/Ersattningsstatus'
          nullable: true
      required:
        - ersattningId

    PatchHandlaggningRequest:
      type: array
      description: Lista med ersättningar att uppdatera beslutsutfall för
      items:
        $ref: '#/components/schemas/UpdateErsattning'

    PatchHandlaggningResponse:
      type: object
      description: Svar vid uppdatering av beslutsutfall i handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning
