openapi: 3.0.3
info:
  title: Handläggning API
  version: 1.0.2
  description: API för att hämta och lagra handläggningsinformation.

paths:
  /handlaggning:
    post:
      tags: [HandlaggningController]
      operationId: postHandlaggning
      summary: Skapa en ny handläggning
      description: Skapa en ny handläggning för ett specifikt yrkande
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yrkandeId:
                  type: string
                  format: uuid
                  description: Yrkandets id
              required:
                - yrkandeId
      responses:
        '201':
          description: Handläggning skapat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt yrkandeId)

  /handlaggning/{handlaggningId}:
    get:
      tags: [HandlaggningController]
      operationId: getHandlaggning
      summary: Hämta handläggning
      description: Hämta handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Handläggning hämtat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)
    put:
      tags: [HandlaggningController]
      operationId: putHandlaggning
      summary: Uppdatera handläggning
      description: Uppdatera handläggning för handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutHandlaggningRequest'
      responses:
        '200':
          description: Handläggning uppdaterat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)

components:
  schemas:
    Handlaggning:
      type: object
      description: Handläggning, ärendeinstans
      properties:
        id:
          type: string
          description: Handläggningens unika ID
          format: uuid
        version:
          type: string
          description: Handläggningens version
        yrkandeId:
          type: string
          description: Yrkandets unika ID
          format: uuid
        processinstansId:
          type: string
          description: BPMN processinstansens unika ID
          format: uuid
        skapadTS:
          type: string
          description: DateTime när handläggning skapades, enligt ISO 8601
          format: date-time
        avslutadTS:
          type: string
          description: DateTime när handläggning avslutades, enligt ISO 8601
          format: date-time
        handlaggningspecifikation:
          $ref: '#/components/schemas/Handlaggningspecifikation'
      required:
        - id
        - version
        - yrkandeId
        - processinstansId

    UppgiftStatus:
      type: string
      description: Uppgiftens status
      enum:
        - PLANERAD
        - TILLDELAD
        - AVSLUTAD

    Handlaggningspecifikation:
      type: object
      description: Handläggningspecifikation, ärendeslag
      properties:
        id:
          type: string
          description: Handläggningspecifikationens unika ID
          format: uuid
        version:
          type: string
          description: Handläggningspecifikationens version
        bpmn:
          type: string
          description: BPMN processbeskrivning
        namn:
          type: string
          description: Namnet på handläggningspecifikationen
        beskrivning:
          type: string
          description: Beskrivning av handläggningspecifikationen
      required:
        - id
        - version
        - namn
        - beskrivning

    Uppgift:
      type: object
      description: Uppgift
      properties:
        id:
          type: string
          description: Uppgiftens ID
          format: uuid
        version:
          type: string
          description: Uppgiftens version
        skapadTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften skapades, enligt ISO 8601
        utfordTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften utfördes, enligt ISO 8601
          nullable: true
        planeradTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften är planerad att utföras, enligt ISO 8601
          nullable: true
        utforarId:
          type: string
          description: Utförarens ID
          format: uuid
          nullable: true
        handlaggningId:
          type: string
          description: Handläggningens Id
          format: uuid
        uppgiftStatus:
          $ref: '#/components/schemas/UppgiftStatus'
        FSSAinformation:
          $ref: '#/components/schemas/FSSAinformation'
        underlag:
          type: array
          description: Ett eller flera underlag som uppgiften använder sig av
          items:
            $ref: '#/components/schemas/Underlag'
        resultat:
          type: array
          description: Ett eller flera resultat av uppgiften
          items:
            $ref: '#/components/schemas/Resultat'
      required:
        - id
        - version
        - handlaggningId
        - uppgiftStatus

    Underlag:
      type: object
      properties:
        typ:
          type: string
          description: Specificerar vilken typ av underlag det är
        version:
          type: string
          description: Specificerar vilken version av underlags typ det är
        data:
          type: string
          description: All data i underlaget i formatet JSON
      required:
        - typ
        - version
        - data

    Resultat:
      type: object
      properties:
        typ:
          type: string
          description: Specificerar vilken typ av resultat det är
        version:
          type: string
          description: Specificerar vilken version av resultatet det är
        data:
          type: string
          description: All data i resultatet i formatet JSON
      required:
        - typ
        - version
        - data

    FSSAinformation:
      type: string
      enum:
        - HANDLAGGNING_PAGAR
        - VANTAR_PA_INFO_FRAN_ANNAN_PART
        - VANTAR_PA_INFO_FRAN_KUND

    GetHandlaggningResponse:
      type: object
      description: Svar vid hämtning av handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning

    PutHandlaggningRequest:
      type: object
      description: Data som krävs för att uppdatera en handläggning
      properties:
        uppgift:
          $ref: '#/components/schemas/Uppgift'
      required:
        - uppgift

    PutHandlaggningResponse:
      type: object
      description: Svar vid uppdatering av handläggning
      properties:
        uppgift:
          $ref: '#/components/schemas/Uppgift'
      required:
        - uppgift

    PostHandlaggningResponse:
      type: object
      description: Svar vid skapande av en ny handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning
